### ISSUE TITLE
An option to specify a fallback language key on LitteraProvider

### ISSUE THREAD

**Issue by abhagsain** [Assembless/react-littera#14]
**Is your feature request related to a problem? Please describe.**
If we miss adding a key for one language, an empty space shows up in the UI

**Describe the solution you'd like**
It'd be nice if we could specify a fallback language in the provider. Showing an English text is much better than showing nothing.

**Comment by DRFR0ST** [comment]
Finally we were able to add support for fallback on missing language. 
Sorry for letting you wait 3 weeks. The feature is now out with the version `v2.4.0`. :tada:
Let me know if you find any bugs etc.

Thanks you for the feature request, hope the lib will serve you well!

**Comment by abhagsain** [comment]
> Finally we were able to add support for fallback on missing language. Sorry for letting you wait 3 weeks. The feature is now out with the version `v2.4.0`. 🎉 Let me know if you find any bugs etc.
> 
> Thanks you for the feature request, hope the lib will serve you well!

Thank you for shipping this @DRFR0ST 😊 
I'll upgrade my project and let you know if I run into any issues.

**Comment by DRFR0ST** [comment]
Awesome! Thanks @abhagsain !
